'use strict';
/* ══════════════════════════════════════════
   PRACTICANTE EN APUROS 3 · SENA 32-BIT
   10 días de etapa productiva · 5 minijuegos
   ══════════════════════════════════════════ */
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const az=a=>a.map(x=>[Math.random(),x]).sort((p,q)=>p[0]-q[0]).map(p=>p[1]);

/* ── DATOS ── */
const SKINS=['#f4c898','#d99b66','#a86a3c','#6f4526'];
const CAMISAS=['#39a900','#13648c','#8c3df0','#c22e44'];
const ACCS=[
  {id:'cafe',    ico:'☕', precio:150},
  {id:'gafas',   ico:'🤓', precio:250},
  {id:'corbata', ico:'👔', precio:350},
  {id:'gorra',   ico:'🧢', precio:400},
  {id:'audifonos',ico:'🎧',precio:500},
  {id:'medalla', ico:'🏅', precio:800},
  {id:'capa',    ico:'🦸', precio:1200},
  {id:'gato',    ico:'🐱', precio:1500},
  {id:'corona',  ico:'👑', precio:2500},
];
const MEJORAS=[
  {id:'vida',  ico:'💖', precio:600},
  {id:'tiempo',ico:'⏰', precio:700},
  {id:'iman',  ico:'🧲', precio:900},
  {id:'doble', ico:'💰', precio:1000},
  {id:'escudo',ico:'🛡️', precio:1200},
];
/* Dificultad.
   vida   = vidas extra o de menos
   tiempo = factor de tiempo (más alto, más tiempo)
   jefe   = agresividad del jefe
   cant   = cuánto hay que hacer: palabras, rondas, parejas, bugs...
   ritmo  = separación entre eventos (más alto, más lento: más fácil)
   err    = fallos permitidos antes de perder el nivel
   ojeada = segundos que se ve el tablero de memoria antes de taparlo

   Los cuatro últimos son nuevos. Antes la dificultad solo multiplicaba
   tiempo, vidas y jefe, y la curva real iba cableada por día (dia>=5,
   dia>=10): PESADILLA en el día 2 tenía los mismos 12 bugs y las mismas
   rondas que PRÁCTICA, solo que con 20% menos de reloj. El selector
   prometía tres juegos y entregaba uno con el cronómetro cambiado. */
const DIFS=[
  {id:0, ico:'🌱', es:'PRÁCTICA',  en:'PRACTICE',  vida:1,  tiempo:1.3, jefe:0.75, cant:0.75, ritmo:1.3,  err:4, ojeada:5},
  {id:1, ico:'⚔️', es:'NORMAL',    en:'NORMAL',    vida:0,  tiempo:1,   jefe:1,    cant:1,    ritmo:1,    err:3, ojeada:3},
  {id:2, ico:'💀', es:'PESADILLA', en:'NIGHTMARE', vida:-1, tiempo:0.8, jefe:1.35, cant:1.3,  ritmo:0.75, err:2, ojeada:2},
];
const RANGOS=[
  {xp:0,   es:'ASPIRANTE',   en:'APPLICANT'},
  {xp:400, es:'APRENDIZ',    en:'APPRENTICE'},
  {xp:1000,es:'PRACTICANTE', en:'INTERN'},
  {xp:1800,es:'DEV JUNIOR',  en:'JUNIOR DEV'},
  {xp:2800,es:'TITULADO SENA',en:'SENA GRADUATE'},
  {xp:4500,es:'DEV SENIOR',  en:'SENIOR DEV'},
];
const NIVELES=[
  {ico:'☕', tipo:'escribir', es:'PRIMER DÍA',        en:'FIRST DAY',        ses:'Configura tu terminal',      sen:'Set up your terminal'},
  {ico:'🐛', tipo:'bugs',     es:'CAZA-BUGS',          en:'BUG HUNT',         ses:'Aplasta los bugs',           sen:'Squash the bugs'},
  {ico:'🧠', tipo:'memoria',  es:'MEMORIA TÉCNICA',    en:'TECH MEMORY',      ses:'Empareja tecnologías',       sen:'Match the tech pairs'},
  {ico:'🔀', tipo:'simon',    es:'FLUJO GIT',          en:'GIT FLOW',         ses:'Repite la secuencia',        sen:'Repeat the sequence'},
  {ico:'📋', tipo:'quiz',     es:'SUSTENTACIÓN',       en:'ORAL EXAM',        ses:'Responde al jurado',         sen:'Answer the panel'},
  {ico:'🔍', tipo:'review',   es:'CODE REVIEW',        en:'CODE REVIEW',      ses:'Aprueba o rechaza',          sen:'Approve or reject'},
  {ico:'🔥', tipo:'bugs',     es:'BUGS EN PRODUCCIÓN', en:'BUGS IN PROD',     ses:'¡Deploy en viernes!',        sen:'Friday deploy!'},
  {ico:'🧬', tipo:'merge',    es:'CONFLICTO GIT',      en:'MERGE CONFLICT',   ses:'Elige la línea buena',       sen:'Pick the right line'},
  {ico:'🚀', tipo:'simon',    es:'DESPLIEGUE',         en:'DEPLOYMENT',       ses:'Un error y se cae todo',     sen:'One slip and it all falls'},
  {ico:'🎓', tipo:'runner',   es:'EVALUACIÓN FINAL',   en:'FINAL EXAM',       ses:'Sobrevive al último día',    sen:'Survive the last day'},
  /* ── TEMPORADA 2 · EL CONTRATO (días 11-15) ── */
  {ico:'🗄', tipo:'sql',      es:'CONSULTA SQL',       en:'SQL QUERY',        ses:'Arma la consulta en orden',  sen:'Build the query in order'},
  {ico:'🧩', tipo:'regex',    es:'CAZA PATRONES',      en:'PATTERN HUNT',     ses:'Atrapa lo que cumple',       sen:'Catch what matches'},
  {ico:'💣', tipo:'bugs',     es:'BUGS NIVEL 2',       en:'BUGS LEVEL 2',     ses:'Cuidado con las bombas',     sen:'Watch out for bombs'},
  {ico:'🌊', tipo:'simon',    es:'GIT AVANZADO',       en:'ADVANCED GIT',     ses:'Rebase y stash incluidos',   sen:'Rebase and stash included'},
  {ico:'🌙', tipo:'runner',   es:'DEPLOY NOCTURNO',    en:'NIGHT DEPLOY',     ses:'La última prueba',           sen:'The final trial'},
];
/* piezas de consulta en orden correcto (minijuego SQL) */
const SQLS=[
 ['SELECT nombre','FROM aprendices','WHERE nota >= 3','ORDER BY nombre'],
 ['SELECT *','FROM cursos','WHERE activo = 1'],
 ['SELECT email','FROM usuarios','WHERE rol = "admin"','LIMIT 10'],
 ['INSERT INTO logros','(nombre, fecha)','VALUES ("titulado", NOW())'],
 ['UPDATE practicantes','SET contrato = 1','WHERE dias = 10'],
 ['SELECT curso, COUNT(*)','FROM inscritos','GROUP BY curso','HAVING COUNT(*) > 5'],
 ['DELETE FROM bugs','WHERE estado = "resuelto"'],
 ['SELECT titulo','FROM proyectos','WHERE entregado = 0'],
 ['SELECT COUNT(*)','FROM aprendices','WHERE ficha = 2847'],
 ['UPDATE bugs','SET prioridad = "alta"','WHERE reportes > 3'],
 ['SELECT nombre, correo','FROM instructores','ORDER BY nombre ASC','LIMIT 5'],
 ['INSERT INTO asistencia','(aprendiz_id, fecha)','VALUES (17, NOW())'],
 ['DELETE FROM sesiones','WHERE expira < NOW()'],
 ['SELECT ficha, AVG(nota)','FROM notas','GROUP BY ficha','HAVING AVG(nota) >= 4'],
 ['SELECT nombre','FROM fichas','WHERE jornada = "noche"'],
 ['SELECT *','FROM tareas','WHERE vence < NOW()','ORDER BY vence'],
 ['UPDATE cursos','SET cupos = cupos - 1','WHERE id = 12'],
 ['INSERT INTO bugs','(titulo, prioridad)','VALUES ("login roto", "alta")'],
 ['SELECT rol, COUNT(*)','FROM usuarios','GROUP BY rol'],
 ['DELETE FROM borradores','WHERE autor_id = 7'],
 ['SELECT apellido','FROM aprendices','WHERE ficha = 2847','ORDER BY apellido DESC'],
 ['SELECT MAX(nota)','FROM notas','WHERE curso = "bases de datos"'],
 ['UPDATE asistencia','SET estado = "justificada"','WHERE fecha = "2026-03-10"'],
 ['SELECT ficha, MIN(nota)','FROM notas','GROUP BY ficha','HAVING MIN(nota) < 3'],
 ['INSERT INTO instructores','(nombre, area)','VALUES ("Camila", "software")'],
 ['SELECT DISTINCT area','FROM instructores','ORDER BY area'],
 ['SELECT titulo','FROM proyectos','WHERE ficha = 2847','LIMIT 3'],
 ['DELETE FROM notificaciones','WHERE leida = 1'],
];
/* rondas del minijuego regex: patrón + descripción + opciones (se evalúan con RegExp real) */
const REGEXS=[
 {p:'^git',    des:'empieza por "git"',     den:'starts with "git"',  opts:['git push','git status','digit','legit','git!','agitar']},
 {p:'[0-9]',   des:'contiene un número',    den:'contains a digit',   opts:['error 404','v2.0','café','deploy','http 500','commit']},
 {p:'\\.js$',  des:'termina en .js',        den:'ends with .js',      opts:['app.js','index.js','main.css','app.json','node.js','estilos.css']},
 {p:'^[A-Z]+$',des:'solo MAYÚSCULAS',       den:'UPPERCASE only',     opts:['SENA','HTML','Sena','css','API','JsOn']},
 {p:'oo',      des:'tiene doble "o"',       den:'has a double "o"',   opts:['google','loop','ping','logo','cool','polo']},
 {p:'^#',      des:'empieza por "#"',       den:'starts with "#"',    opts:['#app','#id-btn','app#','css #','#fff','col#or']},
 {p:'^npm',   des:'empieza por "npm"',     den:'starts with "npm"',  opts:['npm install','npm run dev','install npm','nmp install','npm test','yarn npm']},
 {p:'[aeiou]{2}',des:'dos vocales seguidas',den:'two vowels in a row',opts:['queue','build','cd ..','stack','audio','test']},
 {p:'^[a-z]+$',des:'solo minúsculas',      den:'lowercase only',     opts:['main','README','deploy','Git','commit','API']},
 {p:'-',       des:'contiene un guion',    den:'contains a hyphen',  opts:['pull-request','main-branch','pullrequest','my_var','ui-kit','snake_case']},
 {p:'^\\d+$', des:'solo dígitos',          den:'digits only',        opts:['404','500','v2','200','12a','3.14']},
 {p:'ing$',   des:'termina en "ing"',      den:'ends with "ing"',    opts:['testing','building','ingreso','strings','singular','linting']},
 {p:'^docker',des:'empieza por "docker"',   den:'starts with "docker"',  opts:['docker run','docker ps','dock','rundocker','docker build','docket']},
 {p:'_',       des:'contiene un guion bajo',  den:'contains an underscore',opts:['mi_var','user_id','miVar','snake_case','kebab-case','total']},
 {p:'^SELECT',des:'empieza por "SELECT"',    den:'starts with "SELECT"',  opts:['SELECT *','SELECT id','select *','DELETE FROM','SELECT COUNT','INSERT INTO']},
 {p:'ar$',    des:'termina en "ar"',         den:'ends with "ar"',        opts:['guardar','borrar','guardado','armar','arbol','enviar']},
 {p:'\\.css$',des:'termina en .css',         den:'ends with .css',        opts:['estilos.css','main.css','css.js','estilos.scss','app.css','csss']},
 {p:'[A-Z]',  des:'tiene alguna mayúscula',  den:'has an uppercase letter',opts:['README','miVar','todo','App.js','indice','SENA']},
 {p:'^v[0-9]',des:'empieza por v y número',  den:'starts with v + digit',  opts:['v1','v2.0','version','v10','vue','v3']},
 {p:'ss',     des:'tiene doble "s"',         den:'has a double "s"',      opts:['class','pass','post','assets','session','base']},
 {p:'^/',     des:'empieza por barra',       den:'starts with a slash',   opts:['/api','/home','api/','//dos','/users/1','http://x']},
 {p:'[0-9]{3}',des:'tres dígitos seguidos',  den:'three digits in a row', opts:['404','v2.0','500','12','ficha 2847','año 26']},
 {p:'^git (pu|pull)',des:'git push o git pull',den:'git push or git pull', opts:['git push','git pull','git pu','git commit','git pull -r','pull git']},
 {p:'[.]$',   des:'termina en punto',        den:'ends with a period',    opts:['fin.','listo.','fin!','v2.0','app.js','ok.']},
];
const PALABRAS=['git push','commit','variable','funcion','deploy','servidor','consola','arreglo','objeto','html','css','javascript','python','api rest','frontend','backend','navegador','framework','base de datos','npm install','git status','git clone','console.log','debug','import','export','localhost','software','bucle for','teclado','git merge','git branch','pull request','terminal','repositorio','algoritmo','condicional','parametro','constante','metodo','clase','herencia','interfaz','json','endpoint','peticion get','respuesta','componente','evento','promesa','asincrono','modulo','dependencia','entorno','despliegue','git log','git diff','punto y coma','bucle while','tipo de dato'];
/* Máximo 5 caracteres: la carta de memoria es cuadrada y el texto va a 11px.
   Con 24 el tablero deja de ser siempre el mismo y el repaso espaciado
   puede sesgar hacia las parejas que se te resisten. */
const PAREJAS=['HTML','CSS','JS','SQL','GIT','API','PHP','SENA',
 'JSON','HTTP','NODE','REACT','VUE','JAVA','RUBY','GO',
 'RUST','BASH','NPM','DOM','REST','CRUD','UML','SSH'];
const CODIGO=[
 {c:'const suma = a + b;',ok:1},
 {c:'console.log("hola mundo");',ok:1},
 {c:'for(let i=0; i<10; i++){ }',ok:1},
 {c:'if(x === 5){ y++; }',ok:1},
 {c:'let lista = [1, 2, 3];',ok:1},
 {c:'function saludar(){ return "hey"; }',ok:1},
 {c:'const PI = 3.1416;',ok:1},
 {c:'document.querySelector("#app");',ok:1},
 {c:'if(x = 5){ y++; }',ok:0},
 {c:'console.log("hola mundo"',ok:0},
 {c:'const 1nombre = "ana";',ok:0},
 {c:'retrun x + 1;',ok:0},
 {c:'let a == 3;',ok:0},
 {c:'if(x > 5 { y--; }',ok:0},
 {c:'costn b = 2;',ok:0},
 {c:'for(let i=0; i<10; i++{ }',ok:0},
 {c:'const nombres = lista.map(x => x.nombre);',ok:1},
 {c:'let contador = 0; contador += 1;',ok:1},
 {c:'export default function App(){}',ok:1},
 {c:'const { id, nombre } = usuario;',ok:1},
 {c:'arr.filter(n => n > 10);',ok:1},
 {c:'try{ leer(); }catch(e){ avisar(e); }',ok:1},
 {c:'const nombres = lista.map(x => x.nombre;',ok:0},
 {c:'let contador = 0; contador ++= 1;',ok:0},
 {c:'export defualt function App(){}',ok:0},
 {c:'const { id, nombre = usuario;',ok:0},
 {c:'whlie(i < 5){ i++; }',ok:0},
 {c:'document.querySelectorAll("#app";',ok:0},
 {c:'const [a, b] = pares;',ok:1},
 {c:'items.reduce((t, n) => t + n, 0);',ok:1},
 {c:'if(lista.length > 0){ mostrar(); }',ok:1},
 {c:'switch(tipo){ case 1: ver(); break; }',ok:1},
 {c:'const copia = { ...usuario };',ok:1},
 {c:'class Perro extends Animal {}',ok:1},
 {c:'const n = Number("42");',ok:1},
 {c:'lista.sort((a, b) => a - b);',ok:1},
 {c:'do { i++; } while(i < 3);',ok:1},
 {c:'const fn = async () => await leer();',ok:1},
 {c:'for(const k in objeto){ ver(k); }',ok:1},
 {c:'texto.replace("a", "b").trim();',ok:1},
 {c:'const [a, b = pares;',ok:0},
 {c:'items.reduce((t, n) => t + n, 0;',ok:0},
 {c:'if(lista.length > 0{ mostrar(); }',ok:0},
 {c:'switch(tipo){ case 1 ver(); break; }',ok:0},
 {c:'const copia = { ... };',ok:0},
 {c:'class Perro extneds Animal {}',ok:0},
 {c:'const n = Number("42";',ok:0},
 {c:'lista.sort((a, b) => => a - b);',ok:0},
 {c:'do { i++; } whlie(i < 3);',ok:0},
 {c:'const fn = async () => awiat leer();',ok:0},
 {c:'for(const k in in objeto){ ver(k); }',ok:0},
 {c:'texto.replace("a", "b").trim(;',ok:0},
];
const CONFLICTOS=[
 ['const total = a + b;','const total = a ++ b;'],
 ['console.log("listo");','console.log("listo);'],
 ['if(edad >= 18){ entrar(); }','if(edad >= 18){ entrar(; }'],
 ['let datos = [];','let datos = ][;'],
 ['function init(){ start(); }','function init(){ start( }'],
 ['const url = "api/v1";','const url = api/v1";'],
 ['for(const x of lista){ usar(x); }','for(const x on lista){ usar(x); }'],
 ['return respuesta.json();','return respuesta.jsno();'],
 ['let total = 0;','let total = ;'],
 ['const nombre = "SENA";','const nombre = "SENA;'],
 ['arr.forEach(x => usar(x));','arr.forEach(x => usar(x);)'],
 ['while(i < 10){ i++; }','while(i < 10}{ i++; }'],
 ['export default App;','export defualt App;'],
 ['import fs from "fs";','import fs form "fs";'],
 ['if(!ok) return null;','if(!ok) retrun null;'],
 ['try{ leer(); }catch(e){}','try{ leer(); }cath(e){}'],
 ['const lista = [1, 2, 3];','const lista = [1, 2, 3;'],
 ['usuario.nombre = "Ana";','usuario..nombre = "Ana";'],
 ['const fn = () => 42;','const fn = () => => 42;'],
 ['items.push(nuevo);','items.push(nuevo;'],
 ['if(a && b){ ok(); }','if(a &&& b){ ok(); }'],
 ['const { id } = req;','const { id = req;'],
 ['return lista.length;','retrun lista.length;'],
 ['const n = parseInt("7", 10);','const n = parseInt("7", 10;'],
 ['await cargar();','awiat cargar();'],
 ['class Api extends Base {}','class Api extends {}'],
 ['const copia = {...a};','const copia = {...};'],
 ['for(const k in obj){}','for(const k in in obj){}'],
 ['try{ x(); }catch(e){}','try{ x(); }catch e{}'],
 ['console.warn("ojo");','console.warn("ojo";'],
 ['let total = a * b;','let total = a ** * b;'],
 ['datos.map(d => d.id);','datos.map(d => d.id;'],
];
/* En pantalla no caben doce botones: nvSimon saca un TABLERO de 4 o 6 de
   este banco, distinto en cada partida. Así el minijuego varía sin apretujar
   la rejilla, y los comandos que fallas salen más.
   nv marca el nivel: los días tempranos solo sortean entre los básicos
   (nv:0). Si rebase o stash pudieran salir el día 4, el día 14 —que se llama
   GIT AVANZADO y promete "rebase y stash incluidos"— dejaría de significar
   nada. */
const CMDS=[
  {id:'pull',  cls:'c-pull',  txt:'GIT PULL',  f:330, nv:0},
  {id:'commit',cls:'c-commit',txt:'GIT COMMIT',f:392, nv:0},
  {id:'push',  cls:'c-push',  txt:'GIT PUSH',  f:494, nv:0},
  {id:'deploy',cls:'c-deploy',txt:'DEPLOY',    f:587, nv:0},
  {id:'merge', cls:'c-merge', txt:'GIT MERGE', f:831, nv:0},
  {id:'fetch', cls:'c-fetch', txt:'GIT FETCH', f:880, nv:0},
  {id:'log',   cls:'c-log',   txt:'GIT LOG',   f:1047,nv:0},
  {id:'diff',  cls:'c-diff',  txt:'GIT DIFF',  f:1175,nv:0},
  /* avanzados: solo a partir de GIT AVANZADO (día 14) */
  {id:'rebase',cls:'c-rebase',txt:'GIT REBASE',f:659, nv:1},
  {id:'stash', cls:'c-stash', txt:'GIT STASH', f:740, nv:1},
  {id:'tag',   cls:'c-tag',   txt:'GIT TAG',   f:988, nv:1},
  {id:'reset', cls:'c-reset', txt:'GIT RESET', f:1319,nv:1},
];
const QUIZ={
 es:[
  {q:'¿Qué significa HTML?',o:['HyperText Markup Language','High Tech Modern Language','Home Tool Markup List'],r:0},
  {q:'¿Qué comando guarda cambios en Git?',o:['git save','git commit','git keep'],r:1},
  {q:'¿Qué es un bug?',o:['Un insecto de oficina','Una función secreta','Un error en el código'],r:2},
  {q:'¿Qué lenguaje da estilos a la web?',o:['CSS','SQL','BIOS'],r:0},
  {q:'¿Qué es una API?',o:['Un tipo de café','Interfaz para comunicar sistemas','Una carpeta oculta'],r:1},
  {q:'¿Qué hace "git push"?',o:['Borra el proyecto','Empuja al practicante','Sube commits al remoto'],r:2},
  {q:'¿Qué es el frontend?',o:['La parte visible de la web','El servidor','El cable de red'],r:0},
  {q:'¿Qué base de datos usa tablas?',o:['MongoDB','MySQL','Excel 97'],r:1},
  {q:'¿Qué es un "commit"?',o:['Una reunión','Un error grave','Una foto de tus cambios'],r:2},
  {q:'¿Para qué sirve CSS Grid?',o:['Maquetar en filas y columnas','Conectar a internet','Comprimir imágenes'],r:0},
  {q:'¿Qué es un pull request?',o:['Un tirón de orejas','Propuesta para integrar cambios','Una petición de vacaciones'],r:1},
  {q:'¿Qué significa "deploy"?',o:['Borrar el código','Renunciar con estilo','Publicar la aplicación'],r:2},
  {q:'¿Qué hace "git clone"?',o:['Copia un repositorio remoto','Borra una rama','Crea un commit'],r:0},
  {q:'¿Qué es el backend?',o:['El fondo de pantalla','La lógica y los datos del servidor','El teclado'],r:1},
  {q:'¿Qué significa SQL?',o:['Sistema de Query Libre','Super Query Lang','Structured Query Language'],r:2},
  {q:'¿Qué es una variable?',o:['Un espacio para guardar un valor','Un error del compilador','Un tipo de cable'],r:0},
  {q:'¿Qué hace "console.log()"?',o:['Apaga el navegador','Muestra un valor en la consola','Guarda el archivo'],r:1},
  {q:'¿Qué es un array?',o:['Una contraseña','Un servidor web','Una lista ordenada de valores'],r:2},
  {q:'¿Qué es una rama (branch) en Git?',o:['Una línea de trabajo paralela','Un error de red','Una carpeta del sistema'],r:0},
  {q:'¿Qué significa el error HTTP 404?',o:['Servidor apagado','Recurso no encontrado','Acceso concedido'],r:1},
  {q:'¿Qué es el "responsive design"?',o:['Un diseño que responde correos','Un tipo de fuente','Un diseño que se adapta a cada pantalla'],r:2},
  {q:'¿Qué hace "npm install"?',o:['Instala las dependencias del proyecto','Formatea el disco','Publica la web'],r:0},
  {q:'¿Qué es el DOM?',o:['Un dominio de internet','La estructura de la página en el navegador','Un lenguaje de bases de datos'],r:1},
  {q:'¿Qué es refactorizar?',o:['Borrar todo y empezar de cero','Cambiar de lenguaje','Mejorar el código sin cambiar lo que hace'],r:2},
  {q:'¿Para qué sirve un "if"?',o:['Para repetir código','Para ejecutar algo solo si se cumple una condición','Para importar librerías'],r:1},
  {q:'¿Qué es un bucle?',o:['Un fallo de red','Un comentario largo','Repetir instrucciones varias veces'],r:2},
  {q:'¿Qué significa CSS?',o:['Cascading Style Sheets','Computer Sytem Setup','Code Style Standard'],r:0},
  {q:'¿Qué es JSON?',o:['Un lenguaje de programación','Un formato para intercambiar datos','Un navegador'],r:1},
  {q:'¿Qué es un framework?',o:['Un monitor externo','Un antivirus','Un conjunto de herramientas y reglas para construir más rápido'],r:2},
  {q:'¿Cuándo aparece un conflicto de merge?',o:['Cuando se acaba el disco','Cuando dos cambios tocan la misma línea','Cuando no hay internet'],r:1},
  {q:'¿Qué es una función?',o:['Un dispositivo de red','Un color del tema','Un bloque de código reutilizable'],r:2},
  {q:'¿Qué hace SELECT en SQL?',o:['Borra una tabla','Consulta datos','Crea un usuario'],r:1},
  {q:'¿Qué es un endpoint?',o:['El final del archivo','Un punto de interrupción','Una dirección donde responde la API'],r:2},
  {q:'¿Qué es depurar (debug)?',o:['Comprimir el proyecto','Buscar y quitar errores','Publicar en producción'],r:1},
  {q:'¿Qué es localhost?',o:['Tu propio equipo actuando como servidor','Un servidor de Google','Una red social'],r:0},
  {q:'¿Qué es una constante?',o:['Un valor que no se reasigna','Una variable sin nombre','Un bucle infinito'],r:0},
  {q:'¿Qué es la accesibilidad web?',o:['Que la página pese poco','Que cualquiera pueda usar la página','Que tenga muchos colores'],r:1},
  {q:'¿Qué muestra "git status"?',o:['El historial completo','Qué archivos cambiaron','Los usuarios conectados'],r:1},
  {q:'¿Qué significa HTTP?',o:['HyperText Transfer Protocol','High Traffic Transfer Port','Home Text Transfer Page'],r:0},
  {q:'¿Qué error HTTP dice "no autorizado"?',o:['200','301','401'],r:2},
  {q:'¿Qué es un "string"?',o:['Una cadena de texto','Un número decimal','Una carpeta'],r:0},
  {q:'¿Qué es un booleano?',o:['Un valor verdadero o falso','Una lista de números','Un tipo de archivo'],r:0},
  {q:'¿Qué compara el operador === ?',o:['Solo el valor','El valor y el tipo','Solo el tipo'],r:1},
  {q:'¿Qué es un comentario en el código?',o:['Una función vacía','Un mensaje de error','Texto que el programa ignora'],r:2},
  {q:'¿Qué es "open source"?',o:['Software de pago','Código abierto que cualquiera puede ver y usar','Un servidor gratis'],r:1},
  {q:'¿Qué es la terminal?',o:['Donde escribes comandos','El último archivo del proyecto','Un tipo de pantalla'],r:0},
  {q:'¿Qué es un IDE?',o:['Un entorno de desarrollo','Un protocolo de red','Una base de datos'],r:0},
  {q:'¿Para qué sirve "git log"?',o:['Para borrar ramas','Para ver el historial de commits','Para instalar paquetes'],r:1},
 ],
 en:[
  {q:'What does HTML stand for?',o:['HyperText Markup Language','High Tech Modern Language','Home Tool Markup List'],r:0},
  {q:'Which command saves changes in Git?',o:['git save','git commit','git keep'],r:1},
  {q:'What is a bug?',o:['An office insect','A secret feature','An error in the code'],r:2},
  {q:'Which language styles the web?',o:['CSS','SQL','BIOS'],r:0},
  {q:'What is an API?',o:['A type of coffee','An interface between systems','A hidden folder'],r:1},
  {q:'What does "git push" do?',o:['Deletes the project','Pushes the intern','Uploads commits to the remote'],r:2},
  {q:'What is the frontend?',o:['The visible part of the web','The server','The network cable'],r:0},
  {q:'Which database uses tables?',o:['MongoDB','MySQL','Excel 97'],r:1},
  {q:'What is a "commit"?',o:['A meeting','A serious error','A snapshot of your changes'],r:2},
  {q:'What is CSS Grid for?',o:['Layout in rows and columns','Connecting to the internet','Compressing images'],r:0},
  {q:'What is a pull request?',o:['An ear pull','A proposal to merge changes','A vacation request'],r:1},
  {q:'What does "deploy" mean?',o:['Delete the code','Quit with style','Publish the application'],r:2},
  {q:'What does "git clone" do?',o:['Copies a remote repository','Deletes a branch','Creates a commit'],r:0},
  {q:'What is the backend?',o:['The desktop wallpaper','The server logic and data','The keyboard'],r:1},
  {q:'What does SQL stand for?',o:['Simple Query Loop','Super Query Lang','Structured Query Language'],r:2},
  {q:'What is a variable?',o:['A place to store a value','A compiler error','A type of cable'],r:0},
  {q:'What does "console.log()" do?',o:['Shuts down the browser','Prints a value to the console','Saves the file'],r:1},
  {q:'What is an array?',o:['A password','A web server','An ordered list of values'],r:2},
  {q:'What is a branch in Git?',o:['A parallel line of work','A network error','A system folder'],r:0},
  {q:'What does the HTTP 404 error mean?',o:['Server is down','Resource not found','Access granted'],r:1},
  {q:'What is responsive design?',o:['A design that answers emails','A type of font','A design that adapts to each screen'],r:2},
  {q:'What does "npm install" do?',o:['Installs the project dependencies','Formats the disk','Publishes the site'],r:0},
  {q:'What is the DOM?',o:['An internet domain','The page structure in the browser','A database language'],r:1},
  {q:'What is refactoring?',o:['Deleting everything and starting over','Switching languages','Improving code without changing what it does'],r:2},
  {q:'What is an "if" for?',o:['To repeat code','To run something only if a condition holds','To import libraries'],r:1},
  {q:'What is a loop?',o:['A network failure','A long comment','Repeating instructions several times'],r:2},
  {q:'What does CSS stand for?',o:['Cascading Style Sheets','Computer Sytem Setup','Code Style Standard'],r:0},
  {q:'What is JSON?',o:['A programming language','A format for exchanging data','A browser'],r:1},
  {q:'What is a framework?',o:['An external monitor','An antivirus','A set of tools and rules to build faster'],r:2},
  {q:'When does a merge conflict appear?',o:['When the disk is full','When two changes touch the same line','When there is no internet'],r:1},
  {q:'What is a function?',o:['A network device','A theme color','A reusable block of code'],r:2},
  {q:'What does SELECT do in SQL?',o:['Drops a table','Queries data','Creates a user'],r:1},
  {q:'What is an endpoint?',o:['The end of the file','A breakpoint','An address where the API answers'],r:2},
  {q:'What is debugging?',o:['Compressing the project','Finding and removing errors','Shipping to production'],r:1},
  {q:'What is localhost?',o:['Your own machine acting as a server','A Google server','A social network'],r:0},
  {q:'What is a constant?',o:['A value that is not reassigned','A variable with no name','An infinite loop'],r:0},
  {q:'What is web accessibility?',o:['That the page is small','That anyone can use the page','That it has many colors'],r:1},
  {q:'What does "git status" show?',o:['The full history','Which files changed','The connected users'],r:1},
  {q:'What does HTTP stand for?',o:['HyperText Transfer Protocol','High Traffic Transfer Port','Home Text Transfer Page'],r:0},
  {q:'Which HTTP error means "unauthorized"?',o:['200','301','401'],r:2},
  {q:'What is a "string"?',o:['A piece of text','A decimal number','A folder'],r:0},
  {q:'What is a boolean?',o:['A true or false value','A list of numbers','A file type'],r:0},
  {q:'What does the === operator compare?',o:['Only the value','The value and the type','Only the type'],r:1},
  {q:'What is a code comment?',o:['An empty function','An error message','Text the program ignores'],r:2},
  {q:'What is "open source"?',o:['Paid software','Open code anyone can read and use','A free server'],r:1},
  {q:'What is the terminal?',o:['Where you type commands','The last file in the project','A kind of screen'],r:0},
  {q:'What is an IDE?',o:['A development environment','A network protocol','A database'],r:0},
  {q:'What is "git log" for?',o:['Deleting branches','Seeing the commit history','Installing packages'],r:1},
 ]
};
const DIALOGOS={
 es:[
  ['INSTRUCTOR','¡Bienvenido a tu etapa productiva! Primero: configura tu terminal. Escribe rápido y sin errores.'],
  ['LÍDER TÉCNICO','El practicante anterior dejó bugs por TODAS partes. ¡Aplástalos antes de que se reproduzcan!'],
  ['COMPAÑERA','Examen sorpresa del instructor: ¿recuerdas qué tecnologías van en pareja?'],
  ['LÍDER TÉCNICO','Te voy a mostrar el flujo de Git del equipo. Repítelo EXACTAMENTE igual.'],
  ['INSTRUCTOR','Hoy sustentas ante el jurado. Respira. No digas "eeeh". Tú puedes.'],
  ['LÍDER TÉCNICO','Hoy revisas los pull requests del equipo. Aprueba el código bueno, rechaza el malo. RÁPIDO.'],
  ['LÍDER TÉCNICO','¡¿QUIÉN HIZO DEPLOY UN VIERNES?! ¡Hay bugs en producción! ¡CORRE!'],
  ['COMPAÑERA','Dos ramas tocaron el mismo archivo... resuelve los conflictos eligiendo la línea que sí compila.'],
  ['LÍDER TÉCNICO','Despliegue final. Un comando fuera de orden y se cae TODO. Sin presión.'],
  ['INSTRUCTOR','Evaluación final: sobrevive tu último día en la oficina y el contrato es tuyo.'],
  ['LÍDER TÉCNICO','¡Firmaste! Primera tarea como junior: el reporte necesita una consulta SQL. Ármala en orden.'],
  ['COMPAÑERA','Hay que filtrar mil logs. Con expresiones regulares es un momento... si sabes leerlas.'],
  ['LÍDER TÉCNICO','Volvieron los bugs... y trajeron BOMBAS de imitación. ¡No las toques!'],
  ['INSTRUCTOR','Vine de visita. Veamos si ya dominas el Git avanzado: rebase y stash incluidos.'],
  ['LÍDER TÉCNICO','Deploy nocturno de fin de mes. Sobrevive la noche y esta empresa es tu casa.'],
 ],
 en:[
  ['INSTRUCTOR','Welcome to your internship! First: set up your terminal. Type fast and clean.'],
  ['TECH LEAD','The last intern left bugs EVERYWHERE. Squash them before they multiply!'],
  ['COWORKER','Pop quiz from the instructor: do you remember which technologies pair up?'],
  ['TECH LEAD',"I'll show you the team's Git flow. Repeat it EXACTLY as shown."],
  ['INSTRUCTOR',"Today you present to the panel. Breathe. Don't say 'uhh'. You got this."],
  ['TECH LEAD',"Today you review the team's pull requests. Approve the good code, reject the bad. FAST."],
  ['TECH LEAD','WHO DEPLOYED ON A FRIDAY?! Bugs in production! RUN!'],
  ['COWORKER','Two branches touched the same file... resolve the conflicts by picking the line that compiles.'],
  ['TECH LEAD','Final deployment. One command out of order and EVERYTHING falls. No pressure.'],
  ['INSTRUCTOR','Final exam: survive your last day at the office and the contract is yours.'],
  ['TECH LEAD','You signed! First task as a junior: the report needs an SQL query. Build it in order.'],
  ['COWORKER','We must filter a thousand logs. With regular expressions it takes a second... if you can read them.'],
  ['TECH LEAD','The bugs are back... and they brought fake BOMBS. Do NOT touch those!'],
  ['INSTRUCTOR','Just visiting. Let\'s see if you master advanced Git now: rebase and stash included.'],
  ['TECH LEAD','End-of-month night deploy. Survive the night and this company is your home.'],
 ]
};
const INTRO={
 es:[
  {ico:'🏢',t:'AÑO 2026. Después de mil hojas de vida, conseguiste tu etapa productiva en TechNova S.A.S.'},
  {ico:'📅',t:'Tienes 10 días para demostrar que mereces el contrato de aprendizaje.'},
  {ico:'😅',t:'Sin presión... bueno, sí. MUCHA presión. ¡Suerte, practicante!'},
 ],
 en:[
  {ico:'🏢',t:'YEAR 2026. After a thousand résumés, you landed your internship at TechNova Inc.'},
  {ico:'📅',t:'You have 10 days to prove you deserve the apprenticeship contract.'},
  {ico:'😅',t:'No pressure... well, yes. A LOT of pressure. Good luck, intern!'},
 ]
};
const FINAL={
 es:[
  {ico:'🎉',t:'Lo lograste. Diez días de bugs, cafés fríos y reuniones que pudieron ser un correo.'},
  {ico:'🤝',t:'El líder técnico sonríe por primera vez en la historia: "Firma aquí, practicante."'},
 ],
 en:[
  {ico:'🎉',t:'You made it. Ten days of bugs, cold coffee and meetings that could have been an email.'},
  {ico:'🤝',t:'The tech lead smiles for the first time in recorded history: "Sign here, intern."'},
 ]
};
const JEFE_INTRO={
 es:[
  {ico:'⚠️',t:'Un momento... el servidor legado tiembla. Algo ENORME salió del código sin documentar.'},
  {ico:'👾',t:'¡EL BUG FINAL ha despertado! Nadie se gradúa sin vencerlo. ¡Toma el teclado, practicante!'},
 ],
 en:[
  {ico:'⚠️',t:'Wait... the legacy server is shaking. Something HUGE crawled out of the undocumented code.'},
  {ico:'👾',t:'THE FINAL BUG has awakened! Nobody graduates without defeating it. Grab the keyboard, intern!'},
 ]
};
const T2_INTRO={
 es:[
  {ico:'📝',t:'¡Firmaste el contrato! Pero relajarte no es opción: ahora las tareas son DE VERDAD.'},
  {ico:'💼',t:'TEMPORADA 2 · EL CONTRATO: cinco días como dev junior. SQL, regex y deploys nocturnos te esperan.'},
 ],
 en:[
  {ico:'📝',t:'You signed the contract! But relaxing is not an option: now the tasks are REAL.'},
  {ico:'💼',t:'SEASON 2 · THE CONTRACT: five days as a junior dev. SQL, regex and night deploys await.'},
 ]
};
const JEFE2_INTRO={
 es:[
  {ico:'🌙',t:'3:00 AM. El deploy terminó... pero algo se mueve en los logs del servidor.'},
  {ico:'👾',t:'¡EL BUG FINAL volvió con sed de venganza! Termina lo que empezaste, junior.'},
 ],
 en:[
  {ico:'🌙',t:'3:00 AM. The deploy is done... but something is moving in the server logs.'},
  {ico:'👾',t:'THE FINAL BUG is back for revenge! Finish what you started, junior.'},
 ]
};
const FINAL2={
 es:[
  {ico:'🌅',t:'Amanece. El servidor respira tranquilo y el café sabe a victoria.'},
  {ico:'🚀',t:'El líder técnico te da la mano: "Ya no eres el nuevo. Eres del equipo."'},
 ],
 en:[
  {ico:'🌅',t:'Dawn breaks. The server hums peacefully and the coffee tastes like victory.'},
  {ico:'🚀',t:'The tech lead shakes your hand: "You are not the new kid anymore. You are one of us."'},
 ]
};
const INTERRUPCIONES={
 es:['¡SE CAYÓ EL WIFI!','¡REUNIÓN SORPRESA EN 5 MIN!','¡EL LÍDER PASA POR TU PUESTO!','¡WINDOWS SE ESTÁ ACTUALIZANDO!','¡LLEGÓ EL DE CALIDAD!'],
 en:['WIFI IS DOWN!','SURPRISE MEETING IN 5 MIN!','THE LEAD IS WALKING BY!','WINDOWS IS UPDATING!','QA JUST SHOWED UP!']
};
/* Los logros llevan su PISTA (pes/pen): la condición exacta para conseguirlo.
   Un icono gris sin explicación no motiva a nadie; saber qué falta, sí. Las
   pistas están copiadas de las condiciones reales del código (los darLogro de
   nucleo.js, minijuegos.js y jefe.js), no inventadas: si una deja de coincidir
   es un error que hay que arreglar aquí. */
const LOGROS=[
  {id:'primer', ico:'🌱', es:'PRIMER DÍA',   en:'FIRST DAY',
   pes:'Pasa el día 1',              pen:'Clear day 1'},
  {id:'perfecto',ico:'🌟',es:'DÍA PERFECTO', en:'PERFECT DAY',
   pes:'Saca ★★★ en un día',         pen:'Get ★★★ on a day'},
  {id:'mitad',  ico:'✅', es:'MEDIA ETAPA',  en:'HALFWAY',
   pes:'Aprueba 8 días',             pen:'Clear 8 days'},
  {id:'comprador',ico:'🛍️',es:'COMPRADOR',  en:'SHOPPER',
   pes:'Compra algo en la tienda',   pen:'Buy anything in the shop'},
  {id:'veloz',  ico:'⚡', es:'DEDOS VELOCES',en:'FAST FINGERS',
   pes:'Las 8 palabras sin fallar',  pen:'All 8 words, no misses'},
  {id:'cerebro',ico:'🧠', es:'MEMORIA ÉLITE',en:'ELITE MEMORY',
   pes:'Memoria en 22 giros o menos',pen:'Memory in 22 flips or less'},
  {id:'gitmaster',ico:'🔀',es:'GIT MASTER',  en:'GIT MASTER',
   pes:'Flujo de Git sin errores',   pen:'Git flow with no errors'},
  {id:'revisor', ico:'🔍', es:'OJO DE HALCÓN',en:'HAWK EYE',
   pes:'Code review sin errores',    pen:'Code review with no errors'},
  {id:'resolutor',ico:'🧬',es:'SIN CONFLICTOS',en:'NO CONFLICTS',
   pes:'Merge sin errores',          pen:'Merge with no errors'},
  {id:'jefe',   ico:'👾', es:'CAZA JEFES',   en:'BOSS HUNTER',
   pes:'Derrota al jefe final',      pen:'Beat the final boss'},
  {id:'titulado',ico:'🎓', es:'TITULADO',    en:'GRADUATE',
   pes:'Termina el día 10',          pen:'Finish day 10'},
  {id:'intacto', ico:'🛡️', es:'INTOCABLE',   en:'UNTOUCHABLE',
   pes:'Al jefe sin recibir golpes', pen:'Beat the boss untouched'},
  {id:'combo',   ico:'🔥', es:'EN RACHA',    en:'ON FIRE',
   pes:'5 cafés seguidos en el runner',pen:'5 coffees in a row (runner)'},
  {id:'coleccionista',ico:'🎁',es:'COLECCIONISTA',en:'COLLECTOR',
   pes:'Compra todos los accesorios',pen:'Buy every accessory'},
  {id:'pesadilla',ico:'💀', es:'MODO PESADILLA',en:'NIGHTMARE MODE',
   pes:'Aprueba un día en PESADILLA',pen:'Clear a day on NIGHTMARE'},
  {id:'sql',     ico:'🗄', es:'DATA MASTER', en:'DATA MASTER',
   pes:'SQL sin errores',            pen:'SQL with no errors'},
  {id:'regex',   ico:'🧩', es:'REGEX NINJA', en:'REGEX NINJA',
   pes:'Regex sin errores',          pen:'Regex with no errors'},
  {id:'contrato',ico:'📝', es:'CONTRATADO',  en:'HIRED',
   pes:'Termina el día 15',          pen:'Finish day 15'},
];
/* ── AYUDA DE CONTROLES ──
   Lo que se enseña la PRIMERA vez que entras a cada tipo de minijuego. El
   juego tiene cuatro formas de control (teclado, táctil, mando y giroscopio)
   y ninguna estaba explicada: el día 1 era adivinar. */
const AYUDA={
 escribir:{ico:'⌨',es:['Escribe el comando en la casilla.','Las letras se ponen verdes si vas bien y subrayadas si no.','Tres fallos y el día se acaba.'],
                 en:['Type the command in the box.','Letters turn green when right, underlined when wrong.','Three misses and the day is over.']},
 bugs:{ico:'🐛',es:['Toca el bug cuando asome.','También valen las teclas 1 a 9, como un teclado numérico sobre la rejilla.','El ☕ da puntos extra. La 💣 los quita.'],
                 en:['Tap the bug when it pops up.','Keys 1 to 9 work too, like a numpad over the grid.','The ☕ gives bonus points. The 💣 takes them away.']},
 memoria:{ico:'🧠',es:['Toca dos cartas para darles la vuelta.','Si son pareja se quedan destapadas.','Cuantos menos giros, más estrellas.'],
                 en:['Tap two cards to flip them.','Matching pairs stay face up.','Fewer flips, more stars.']},
 simon:{ico:'🔀',es:['Mira la secuencia de comandos que se ilumina.','Luego repítela en el mismo orden.','Cada ronda añade un comando más.'],
                 en:['Watch the sequence of commands light up.','Then repeat it in the same order.','Each round adds one more command.']},
 quiz:{ico:'📋',es:['Elige la respuesta que creas correcta.','No hay tiempo: piénsalo.','Lo que falles volverá a salirte más adelante.'],
                 en:['Pick the answer you think is right.','No timer: take your time.','What you miss will come back later.']},
 review:{ico:'🔍',es:['Lee la línea de código.','APRUEBA si está bien escrita, RECHAZA si tiene un error.','Ojo con el = donde debería ir ===.'],
                 en:['Read the line of code.','APPROVE if it is correct, REJECT if it has a bug.','Watch out for = where === belongs.']},
 merge:{ico:'🧬',es:['Dos versiones de la misma línea, una está rota.','Toca la que se quedaría en el proyecto.','Suele fallar un paréntesis o una comilla.'],
                 en:['Two versions of the same line, one is broken.','Tap the one that should stay in the project.','Usually a bracket or a quote is missing.']},
 sql:{ico:'🗄',es:['Arma la consulta tocando las piezas en orden.','Primero SELECT, después FROM, luego WHERE…','Una pieza mal colocada cuenta como error.'],
                 en:['Build the query by tapping the pieces in order.','SELECT first, then FROM, then WHERE…','A piece in the wrong place counts as an error.']},
 regex:{ico:'🧩',es:['Arriba tienes el patrón y qué busca.','Toca SOLO las opciones que lo cumplen.','Tocar una que no cumple cuenta como error.'],
                 en:['The pattern and what it matches are at the top.','Tap ONLY the options that match it.','Tapping one that does not match counts as an error.']},
 runner:{ico:'🎓',es:['◀ ▶ para moverte, ▲ para saltar y ▼ para agacharte.','Con teclado: flechas, o espacio para saltar.','Si tienes mando conectado, también funciona.'],
                 en:['◀ ▶ to move, ▲ to jump and ▼ to duck.','On a keyboard: arrows, or space to jump.','A connected gamepad works too.']},
 jefe:{ico:'👾',es:['◀ ▶ para esquivar; disparas solo.','El botón GIRAR activa el giroscopio: inclina el teléfono para moverte.','Tres fases. Sin recibir un golpe se gana un logro.'],
                 en:['◀ ▶ to dodge; you shoot automatically.','The TILT button turns on the gyroscope: tilt the phone to move.','Three phases. Beat it untouched for an achievement.']},
};
const TXT={
 es:{dia:'DÍA',start:'PULSA START',jugar:'▶ JUGAR',tienda:'TIENDA',logros:'LOGROS',records:'RÉCORDS',perso:'MI AVATAR',
  glob_tit:'🌍 MARCADOR GLOBAL',glob_todas:'TODAS',
  rango_max:'RANGO MÁXIMO',progreso_lbl:'PROGRESO',estad_corto:'STATS',
  perso_sub:'Tu progreso, tu historia',
  flojo_tit:'🎯 EN QUÉ FLOJEAS',
  flojo_txt:'Lo que has fallado y aún no has vuelto a acertar. El juego te lo repite más seguido.',
  flojo_nada:'Nada pendiente de repaso. ¡Vas al día!',
  reto_tit:'RETO DIARIO',reto_racha:'DÍAS SEGUIDOS',reto_ya:'▶ JUGAR EL RETO',
  reto_otra:'🔁 REPETIR (no cuenta)',reto_tabla:'🏁 MARCADOR DE HOY',
  reto_expl:'Tres minijuegos, los mismos para todo el mundo hoy. Solo cuenta tu primer intento.',
  reto_hecho:'Ya jugaste el reto de hoy: {p} puntos. Vuelve mañana para seguir la racha.',
  reto_nadie:'Nadie ha jugado el reto de hoy todavía. ¡Sé el primero!',
  reto_prox:'Siguiente premio: {i} a los {d} días seguidos',
  reto_ronda:'RONDA {n}/{t}',reto_fin:'¡RETO COMPLETADO!',reto_rondas:'{a} de {t} rondas superadas',
  reto_perdon:'🛟 Te saltaste un día, pero se te perdona (uno al mes).',
  reto_repe:'Repetición de práctica: {p} puntos. No cuenta para la racha.',
  st_retos:'RETOS DIARIOS',
  tipo_escribir:'MECANOGRAFÍA',tipo_bugs:'CAZA-BUGS',tipo_memoria:'MEMORIA',tipo_simon:'FLUJO GIT',
  tipo_quiz:'QUIZ',tipo_review:'CODE REVIEW',tipo_merge:'CONFLICTOS',tipo_sql:'SQL',tipo_regex:'REGEX',
  tipo_palabras:'COMANDOS',tipo_git:'FLUJO GIT',glob_loc:'💾 TUS MARCAS',glob_carga:'CONSULTANDO…',
  glob_sinred:'Sin conexión con el marcador. Abajo siguen tus marcas locales.',
  glob_vacio:'Nadie ha publicado todavía. ¡Sé el primero!',
  glob_locvacio:'Termina el día 5 para registrar tu primera marca.',
  sub:'LA AVENTURA DEL APRENDIZ · CAPÍTULO 4',mapa:'MAPA DE PRÁCTICA',volver:'← VOLVER',continuar:'CONTINUAR',
  pausa:'PAUSA',salirmapa:'SALIR AL MAPA',empezar:'¡EMPEZAR!',listo:'¿LISTO?',aqui:'AQUÍ',
  aprobado:'¡DÍA SUPERADO!',fallado:'¡DÍA FALLIDO!',reintentar:'REINTENTAR',siguiente:'SIGUIENTE DÍA ▶',
  gameover:'GAME OVER',gameovertxt:'Te quedaste sin vidas. El instructor te manda a tomar aire y volver mañana.',
  ptsgan:'PTS GANADOS',mejor:'MEJOR',bloqueado:'Completa el día anterior',
  tiempo:'TIEMPO',meta:'META',errores:'ERRORES',ronda:'RONDA',pares:'PARES',golpes:'GOLPES',cafes:'CAFÉS',
  casilla:'Casilla',bugs_teclas:'⌨ También con las teclas 1-9',
  escribeaqui:'ESCRIBE AQUÍ',observa:'OBSERVA...',turno:'¡TU TURNO!',
 memoriza:'MEMORIZA...',memo_ya:'¡A BUSCARLAS!',
  toca:'TOCA PARA SEGUIR',saltar:'SALTAR ▶▶',pagina:'PÁG',
  runmsg:'▲ SALTA · ▼ AGÁCHATE · esquiva bugs y papeleo, agarra café',
  cert:'CERTIFICADO OFICIAL',certde:'Se certifica que',certtxt:'completó sus 10 días de etapa productiva sin llorar (mucho)',
  firma:'FIRMA: EL INSTRUCTOR',fecha:'FECHA',
  rango:'RANGO',rangos:'ESCALAFÓN',stats:'ESTADÍSTICAS',diascomp:'DÍAS',estrellas:'ESTRELLAS',ptstotal:'PTS TOTALES',
  comprar:'COMPRAR',equipado:'EQUIPADO',mejoras:'MEJORAS DE OFICINA',
  mejvida:'VIDA EXTRA',mejtiempo:'+20% TIEMPO',mejdoble:'PUNTOS ×2',
  acc_cafe:'CAFÉ ETERNO',acc_gafas:'GAFAS DEV',acc_corbata:'CORBATA',acc_gorra:'GORRA',acc_audifonos:'AUDÍFONOS',acc_medalla:'MEDALLA',
  logro:'¡LOGRO DESBLOQUEADO!',sinacc:'SIN ACCESORIO',piel:'PIEL',camisa:'CAMISA',accesorio:'ACCESORIO',
  rec_nom:'NOMBRE',rec_pts:'PTS',rec_rango:'RANGO',tu:'TÚ',
  quiznec:'Necesitas 4 de 6 para aprobar',
  vidas_txt:'VIDAS',
  nombreq:'¿CÓMO TE LLAMAS?',tunombre:'TU NOMBRE',ok:'¡LISTO!',
  combo:'RACHA',
  aprobar:'✔ APROBAR',rechazar:'✘ RECHAZAR',lineasrev:'LÍNEAS',
  eligebuena:'Toca la línea que SÍ compila',
  modo_hd:'✨ MODO 4K HD OLED',modo_retro:'🕹 MODO RETRO 32-BIT',
  texto_legible:'🔤 TEXTO LEGIBLE',texto_pixel:'🕹 TEXTO PIXEL',
  ayuda_tit:'CÓMO SE JUEGA',ayuda_ok:'ENTENDIDO',ayuda_nota:'Solo se enseña la primera vez',
  grupo_tit:'CÓDIGO DE AULA',grupo_no:'Sin grupo',grupo_unirse:'UNIRME',grupo_cambiar:'CAMBIAR',
  grupo_solo:'SOLO MI GRUPO',grupo_salir:'Salir del grupo',grupo_ph:'SENA2847',
  grupo_malo:'De 3 a 8 letras o números',
  grupo_txt:'Escribe el código que reparta tu instructor y compite con tu ficha. Cualquiera que sepa el código ve ese marcador: es un tablero de clase, no una contraseña.',
  borrar:'🗑 BORRAR PROGRESO',seguro:'¿ESTÁS SEGURO?',
  borrartxt:'Se borrará TODO tu progreso: días, estrellas, puntos, logros, compras y récords. El idioma, el sonido y el modo visual se conservan. Esta acción NO se puede deshacer.',
  perderas:'PERDERÁS',sioborrar:'SÍ, BORRAR TODO',cancelar:'CANCELAR',
  borrado:'PROGRESO BORRADO. ¡PARTIDA NUEVA!',
  jefemsg:'◀ ▶ MUÉVETE · disparas solo · esquiva los ❌ · sirve mando 🎮 o inclinar 📱',
  girar:'📱 GIRO',mando:'¡MANDO CONECTADO!',
  jefereplay:'Repetir batalla del jefe',
  dificultad:'DIFICULTAD',estadisticas:'📈 ESTADÍSTICAS',
  st_bugs:'BUGS APLASTADOS',st_cafes:'CAFÉS TOMADOS',st_palabras:'PALABRAS ESCRITAS',
  st_jefes:'JEFES VENCIDOS',st_perfectos:'DÍAS PERFECTOS',st_racha:'MEJOR RACHA',
  st_partidas:'PARTIDAS TERMINADAS',st_sinreg:'Aún no hay datos. ¡A jugar!',
  compartir:'📤 COMPARTIR',copiado:'¡COPIADO AL PORTAPAPELES!',
  compartexto:'Terminé Practicante en Apuros 4 con {p} pts como {r} 🎓 ¡Juégalo!',
  jefefase:'FASE',avisolaser:'¡LÁSER!',
  guardado:'💾 CÓDIGO DE GUARDADO',exportar:'📤 EXPORTAR PARTIDA',importar:'📥 IMPORTAR',
  pegacodigo:'Pega aquí tu código PA4...',impok:'¡PARTIDA IMPORTADA!',impmal:'CÓDIGO INVÁLIDO',
  guardatxt:'Exporta tu partida y pégala en otro dispositivo para continuar allí.',
  t1sec:'🎓 ETAPA PRODUCTIVA',t2sec:'📝 EL CONTRATO',
  sqlmsg:'Toca las piezas en ORDEN para armar la consulta',objetivo:'OBJETIVO',
  regexmsg:'Toca TODO lo que cumpla el patrón',patron:'PATRÓN',
  acc_capa:'CAPA DE HÉROE',acc_gato:'GATO DE OFICINA',acc_corona:'CORONA DEV',
  mejiman:'CAFÉ PREMIUM',mejescudo:'ESCUDO DEV',
  d_vida:'Una vida extra cada día',d_tiempo:'+20% de tiempo en los retos',
  d_doble:'Ganas el doble de puntos',d_iman:'Los cafés valen más puntos',
  d_escudo:'Anula tu primer golpe en el runner y el jefe',
  ascenso:'¡CONTRATO INDEFINIDO!',ascensode:'La empresa confirma que',
  ascensotxt:'sobrevivió sus primeros 5 días como dev junior y ya es parte del equipo',
 },
 en:{dia:'DAY',start:'PRESS START',jugar:'▶ PLAY',tienda:'SHOP',logros:'AWARDS',records:'RECORDS',perso:'MY AVATAR',
  glob_tit:'🌍 GLOBAL LEADERBOARD',glob_todas:'ALL',
  rango_max:'MAX RANK',progreso_lbl:'PROGRESS',estad_corto:'STATS',
  perso_sub:'Your progress, your story',
  flojo_tit:'🎯 WHAT TO REVIEW',
  flojo_txt:'What you got wrong and have not nailed since. The game brings it back sooner.',
  flojo_nada:'Nothing left to review. You are up to date!',
  reto_tit:'DAILY CHALLENGE',reto_racha:'DAY STREAK',reto_ya:'▶ PLAY THE CHALLENGE',
  reto_otra:'🔁 REPLAY (does not count)',reto_tabla:"🏁 TODAY'S BOARD",
  reto_expl:'Three minigames, the same for everyone today. Only your first try counts.',
  reto_hecho:"You already played today's challenge: {p} points. Come back tomorrow to keep the streak.",
  reto_nadie:'Nobody has played today yet. Be the first!',
  reto_prox:'Next reward: {i} at {d} days in a row',
  reto_ronda:'ROUND {n}/{t}',reto_fin:'CHALLENGE COMPLETE!',reto_rondas:'{a} of {t} rounds cleared',
  reto_perdon:'🛟 You missed a day, but it is forgiven (one per month).',
  reto_repe:'Practice replay: {p} points. It does not count for the streak.',
  st_retos:'DAILY CHALLENGES',
  tipo_escribir:'TYPING',tipo_bugs:'BUG HUNT',tipo_memoria:'MEMORY',tipo_simon:'GIT FLOW',
  tipo_quiz:'QUIZ',tipo_review:'CODE REVIEW',tipo_merge:'CONFLICTS',tipo_sql:'SQL',tipo_regex:'REGEX',
  tipo_palabras:'TYPING',tipo_git:'GIT FLOW',glob_loc:'💾 YOUR SCORES',glob_carga:'LOADING…',
  glob_sinred:'No connection to the leaderboard. Your local scores are still below.',
  glob_vacio:'Nobody has posted a score yet. Be the first!',
  glob_locvacio:'Finish day 5 to record your first score.',
  sub:'THE APPRENTICE ADVENTURE · CHAPTER 4',mapa:'INTERNSHIP MAP',volver:'← BACK',continuar:'CONTINUE',
  pausa:'PAUSED',salirmapa:'EXIT TO MAP',empezar:'START!',listo:'READY?',aqui:'HERE',
  aprobado:'DAY CLEARED!',fallado:'DAY FAILED!',reintentar:'RETRY',siguiente:'NEXT DAY ▶',
  gameover:'GAME OVER',gameovertxt:'You ran out of lives. The instructor sends you home to try again tomorrow.',
  ptsgan:'PTS EARNED',mejor:'BEST',bloqueado:'Clear the previous day',
  tiempo:'TIME',meta:'GOAL',errores:'ERRORS',ronda:'ROUND',pares:'PAIRS',golpes:'HITS',cafes:'COFFEES',
  casilla:'Cell',bugs_teclas:'⌨ Keys 1-9 work too',
  escribeaqui:'TYPE HERE',observa:'WATCH...',turno:'YOUR TURN!',
  memoriza:'MEMORISE...',memo_ya:'GO FIND THEM!',
  toca:'TAP TO CONTINUE',saltar:'SKIP ▶▶',pagina:'PAGE',
  runmsg:'▲ JUMP · ▼ DUCK · dodge bugs and paperwork, grab coffee',
  cert:'OFFICIAL CERTIFICATE',certde:'This certifies that',certtxt:'completed 10 days of internship without crying (much)',
  firma:'SIGNED: THE INSTRUCTOR',fecha:'DATE',
  rango:'RANK',rangos:'RANKS',stats:'STATS',diascomp:'DAYS',estrellas:'STARS',ptstotal:'TOTAL PTS',
  comprar:'BUY',equipado:'EQUIPPED',mejoras:'OFFICE UPGRADES',
  mejvida:'EXTRA LIFE',mejtiempo:'+20% TIME',mejdoble:'POINTS ×2',
  acc_cafe:'ETERNAL COFFEE',acc_gafas:'DEV GLASSES',acc_corbata:'TIE',acc_gorra:'CAP',acc_audifonos:'HEADPHONES',acc_medalla:'MEDAL',
  logro:'ACHIEVEMENT UNLOCKED!',sinacc:'NO ACCESSORY',piel:'SKIN',camisa:'SHIRT',accesorio:'ACCESSORY',
  rec_nom:'NAME',rec_pts:'PTS',rec_rango:'RANK',tu:'YOU',
  quiznec:'You need 4 of 6 to pass',
  vidas_txt:'LIVES',
  nombreq:'WHAT IS YOUR NAME?',tunombre:'YOUR NAME',ok:'DONE!',
  combo:'STREAK',
  aprobar:'✔ APPROVE',rechazar:'✘ REJECT',lineasrev:'LINES',
  eligebuena:'Tap the line that DOES compile',
  modo_hd:'✨ 4K HD OLED MODE',modo_retro:'🕹 RETRO 32-BIT MODE',
  texto_legible:'🔤 READABLE TEXT',texto_pixel:'🕹 PIXEL TEXT',
  ayuda_tit:'HOW TO PLAY',ayuda_ok:'GOT IT',ayuda_nota:'Shown only the first time',
  grupo_tit:'CLASS CODE',grupo_no:'No group',grupo_unirse:'JOIN',grupo_cambiar:'CHANGE',
  grupo_solo:'MY GROUP ONLY',grupo_salir:'Leave the group',grupo_ph:'CLASS284',
  grupo_malo:'3 to 8 letters or digits',
  grupo_txt:'Enter the code your instructor hands out and compete with your class. Anyone who knows the code can see that board: it is a classroom scoreboard, not a password.',
  borrar:'🗑 DELETE PROGRESS',seguro:'ARE YOU SURE?',
  borrartxt:'ALL your progress will be deleted: days, stars, points, achievements, purchases and records. Language, sound and visual mode are kept. This CANNOT be undone.',
  perderas:'YOU WILL LOSE',sioborrar:'YES, DELETE EVERYTHING',cancelar:'CANCEL',
  borrado:'PROGRESS DELETED. FRESH START!',
  jefemsg:'◀ ▶ MOVE · auto-fire · dodge the ❌ · gamepad 🎮 or tilt 📱 works',
  girar:'📱 TILT',mando:'GAMEPAD CONNECTED!',
  jefereplay:'Replay the final boss',
  dificultad:'DIFFICULTY',estadisticas:'📈 STATISTICS',
  st_bugs:'BUGS SQUASHED',st_cafes:'COFFEES DRUNK',st_palabras:'WORDS TYPED',
  st_jefes:'BOSSES BEATEN',st_perfectos:'PERFECT DAYS',st_racha:'BEST STREAK',
  st_partidas:'GAMES FINISHED',st_sinreg:'No data yet. Go play!',
  compartir:'📤 SHARE',copiado:'COPIED TO CLIPBOARD!',
  compartexto:'I finished Intern in Trouble 4 with {p} pts as {r} 🎓 Play it!',
  jefefase:'PHASE',avisolaser:'LASER!',
  guardado:'💾 SAVE CODE',exportar:'📤 EXPORT SAVE',importar:'📥 IMPORT',
  pegacodigo:'Paste your PA4 code here...',impok:'SAVE IMPORTED!',impmal:'INVALID CODE',
  guardatxt:'Export your save and paste it on another device to continue there.',
  t1sec:'🎓 INTERNSHIP',t2sec:'📝 THE CONTRACT',
  sqlmsg:'Tap the pieces IN ORDER to build the query',objetivo:'GOAL',
  regexmsg:'Tap EVERYTHING that matches the pattern',patron:'PATTERN',
  acc_capa:'HERO CAPE',acc_gato:'OFFICE CAT',acc_corona:'DEV CROWN',
  mejiman:'PREMIUM COFFEE',mejescudo:'DEV SHIELD',
  d_vida:'One extra life each day',d_tiempo:'+20% time on challenges',
  d_doble:'Earn double points',d_iman:'Coffees are worth more points',
  d_escudo:'Blocks your first hit in the runner and boss',
  ascenso:'PERMANENT CONTRACT!',ascensode:'The company confirms that',
  ascensotxt:'survived their first 5 days as a junior dev and is now part of the team',
 }
};
